/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ulti.java
 *
 * Created on 16-jun-2013, 23:40:34
 */
package formularioderequerimientodeproductoservicio;

import Logica.ControladorLogica;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.ScrollPane;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walter
 */
public class ulti extends javax.swing.JFrame {
    private ControladorLogica cl;
    //private static ArrayList <HashMap>;
    private static DefaultTableModel ingresoDatos;
    private  String[] resultado= new String[9];
    private static String[] nombreTabla= {"N°Formulario","Descripcion En detalle del Requerimiento","Producto/Servicio","Cantidad","Precio Estimado Unitario Neto","Valor Estimado Total por Item Neto","Valor total Pesos neto","Impuesto","Total Pesos"};
    //"Descripcion En detalle del Requerimiento","Producto/Servicio","Cantidad","Valor moneda","Valor Estimado unitario Item Neto", "impuesto","Valor total Pesos"
    private static int valor=0;
    private static  HashMap <String, String[]> myMap = new HashMap<String, String[]>();
    private static final long serialVersionUID = 1L;
    private static double sumaimp=0;
    private ScrollPane elSP;
   
    /** Creates new form ulti */
    public ulti() {
       initComponents();
       this.setBounds(0, 0, 500, 500);
       PanelFondo F= new PanelFondo();
       OtroPanel f2= new OtroPanel();
       this.add(F,BorderLayout.CENTER);
      // this.jPanel1.add(f2,BorderLayout.CENTER);
      
       this.pack();
       
       cl= new ControladorLogica();
       
        jLabel15.setText("Usuario en el sistema : "+Login.nom);
      
       int numero= cl.BuscarNumeroCorrelativo();
        ingresoDatos = new DefaultTableModel(null, nombreTabla);
        String num= String.valueOf(numero);        
        Dtecnum.setText(num);
        Dtecnum.setEditable(false);    
        
        
       buttonGroup1.add(SeisDias);
       buttonGroup1.add(DiezDias);
       buttonGroup1.add(VeinteDias); 
       buttonGroup2.add(Producto);
       buttonGroup2.add(TrabajoSer);
       buttonGroup2.add(AsesoConsul);
       
       buttonGroup3.add(StockBodeSi);
       buttonGroup3.add(StockBodeNo);
       
       buttonGroup4.add(AnexoSi);
       buttonGroup4.add(AnexoNo);
       

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PeriUso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Cargo = new javax.swing.JTextField();
        Solicitante = new javax.swing.JTextField();
        Recibe = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        HoraRecep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Dtecnum = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        DescipGeneDelProSer = new javax.swing.JTextField();
        MotivosDelaNecesidadyDestino = new javax.swing.JTextField();
        RecomendaProve = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        ValorMoneda1 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        ItemAsignac = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        Saldo = new javax.swing.JTextField();
        AsigPptariaSubt = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DescripDeReq1 = new javax.swing.JTextField();
        ValEstiToNe1 = new javax.swing.JTextField();
        ProdSer1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ValEst = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        VBFinanzas = new javax.swing.JCheckBox();
        VBAdquisiciones = new javax.swing.JCheckBox();
        Cantidad1 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        TipoCompra = new javax.swing.JComboBox();
        SeisDias = new javax.swing.JRadioButton();
        DiezDias = new javax.swing.JRadioButton();
        VeinteDias = new javax.swing.JRadioButton();
        Producto = new javax.swing.JRadioButton();
        TrabajoSer = new javax.swing.JRadioButton();
        AsesoConsul = new javax.swing.JRadioButton();
        StockBodeSi = new javax.swing.JRadioButton();
        StockBodeNo = new javax.swing.JRadioButton();
        AnexoSi = new javax.swing.JRadioButton();
        AnexoNo = new javax.swing.JRadioButton();
        MoDeRe = new javax.swing.JComboBox();
        ProBusOf = new javax.swing.JComboBox();
        DeptoYUni = new javax.swing.JComboBox();
        Impuesto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ValorTPesos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JTextField();
        FechaRecep = new javax.swing.JTextField();
        DefineImpuesto = new javax.swing.JComboBox();
        ValorMoneda = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText(" 2013  N° De Formulario:");

        jLabel2.setText("Fechar recepcion para publicacion en marcadopublico.cl ");

        jLabel9.setText("Fecha");

        jLabel7.setText("Plazo publicacion solicitado ");

        jLabel8.setText("Clase de Requerimiento");

        jLabel5.setText("Recibe");

        PeriUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeriUsoActionPerformed(evt);
            }
        });

        jLabel11.setText("Solicitante");

        jLabel12.setText("Cargo");

        jLabel10.setText("Depto. y/o Unidad");

        jLabel13.setText("Periodo de Uso");

        Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha ");

        jLabel4.setText("Hora");

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel23.setText("Stock en Bodega");

        jLabel20.setText("Tipo De Compra");

        Dtecnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DtecnumActionPerformed(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel52.setText("Ingreso de Formulario De Requerimiento De Producto y/o Servicios");

        jLabel31.setText("Motivo de recomendacion ( CM,TD,<3UTM)");

        jLabel35.setText("¿Anexo?");

        DescipGeneDelProSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescipGeneDelProSerActionPerformed(evt);
            }
        });

        RecomendaProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecomendaProveActionPerformed(evt);
            }
        });

        jLabel26.setText("Descripcion general de Producto / Servicio");

        jLabel29.setText("Procedimientos de busqueda oferentes  (CM,LP,TD,<3UTM)");

        jLabel27.setText("Motivos de la necesidad y destino final del producto y/o servicio");

        jLabel30.setText("Recomendacion de proveedores");

        jButton1.setText("Guardar Formulario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel58.setText("Valor de Moneda en pesos a la fecha");

        jLabel53.setText("Descripcion en Detalle del Requerimiento");

        jLabel57.setText("Valor Estimado Unitario Neto en Moneda especifica");

        jLabel54.setText("Producto/Servicio");

        jLabel43.setText("Asig PPTARIA");

        jLabel55.setText("Cantidad");

        jLabel44.setText("SUBT.");

        AsigPptariaSubt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsigPptariaSubtActionPerformed(evt);
            }
        });

        jLabel46.setText("SALDO PPTARIO M$");

        jLabel47.setText("V° B° finanzas");

        jLabel45.setText("ITEM/ASIGNAC.");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ValEstiToNe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValEstiToNe1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar Producto/Servicio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel48.setText("V° B° Adquisiciones");

        VBAdquisiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VBAdquisicionesActionPerformed(evt);
            }
        });

        Cantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cantidad1ActionPerformed(evt);
            }
        });

        jLabel50.setText("$");

        jLabel49.setText("Valor estimado (impto. Incl.)");

        TipoCompra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rutinaria", "Estrategica" }));
        TipoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoCompraActionPerformed(evt);
            }
        });

        SeisDias.setText(" +6 dias < 100 utm");

        DiezDias.setText("+10 dias >100<1000 utm ");
        DiezDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiezDiasActionPerformed(evt);
            }
        });

        VeinteDias.setText("+20 dias > 1000 utm");
        VeinteDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeinteDiasActionPerformed(evt);
            }
        });

        Producto.setText("Producto");

        TrabajoSer.setText("Trabajo/Servicio");

        AsesoConsul.setText("Asesoria/Consultoria");

        StockBodeSi.setText("Si");

        StockBodeNo.setText("No");

        AnexoSi.setText("Si");

        AnexoNo.setText("No");
        AnexoNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnexoNoActionPerformed(evt);
            }
        });

        MoDeRe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CM", "TD", "<3UTM" }));

        ProBusOf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CM", "LP", "TD", "<3UTM", "100 UTM< entre >1000 UTM", "<1000 UTM" }));

        DeptoYUni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Division Tecnica", "Administración y Finanzas", "Auditoría Interna", "Ingeniería y Desarrollo", "Operaciones", "Gestion de Personas", "Calibraciones" }));
        DeptoYUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeptoYUniActionPerformed(evt);
            }
        });

        jLabel1.setText("Impuesto");

        jLabel14.setText("Valor de todo estimado en pesos");

        FechaRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaRecepActionPerformed(evt);
            }
        });

        DefineImpuesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IVA 19%", "Excento de Impuesto", "Impuesto 10%" }));
        DefineImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefineImpuestoActionPerformed(evt);
            }
        });

        ValorMoneda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UF", "DOLAR", "UTM", "PESOS" }));
        ValorMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorMonedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DescripDeReq1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel53)
                                .addGap(5, 5, 5)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54)
                            .addComponent(ProdSer1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel55)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel57))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Cantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(ValEstiToNe1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DefineImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(RecomendaProve)
                                        .addComponent(MotivosDelaNecesidadyDestino)
                                        .addComponent(DescipGeneDelProSer, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                                        .addComponent(ProBusOf, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(MoDeRe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(AnexoSi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AnexoNo))))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(338, 338, 338)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AsigPptariaSubt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel44))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ItemAsignac, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel46)
                                            .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(VBFinanzas)
                                            .addComponent(jLabel47))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel48)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel49)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(Impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ValorTPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel14)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(VBAdquisiciones)
                                                .addGap(73, 73, 73)
                                                .addComponent(jLabel50)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                                                .addComponent(ValEst, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(12, 12, 12)))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(ValorMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel58)
                                    .addComponent(ValorMoneda1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel13))
                                        .addGap(131, 131, 131)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Solicitante, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                            .addComponent(Cargo, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                            .addComponent(PeriUso, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                            .addComponent(FechaRecep)
                                            .addComponent(DeptoYUni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HoraRecep, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(Recibe))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StockBodeSi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(StockBodeNo))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(DiezDias)
                                            .addComponent(SeisDias)
                                            .addComponent(VeinteDias)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(TrabajoSer)
                                            .addComponent(Producto)
                                            .addComponent(AsesoConsul)
                                            .addComponent(Dtecnum, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HoraRecep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Recibe))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FechaRecep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeptoYUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Solicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PeriUso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dtecnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Producto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TrabajoSer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AsesoConsul))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(DiezDias))
                                    .addComponent(SeisDias))
                                .addGap(5, 5, 5)
                                .addComponent(VeinteDias)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(TipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(StockBodeSi)
                            .addComponent(StockBodeNo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescipGeneDelProSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MotivosDelaNecesidadyDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(ProBusOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecomendaProve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MoDeRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(AnexoSi)
                            .addComponent(AnexoNo))
                        .addGap(157, 157, 157)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(jLabel54)
                    .addComponent(jLabel55)
                    .addComponent(jLabel57))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProdSer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescripDeReq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValEstiToNe1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DefineImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel58)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorMoneda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(ValEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValorTPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43)
                            .addComponent(jLabel49)
                            .addComponent(Impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ItemAsignac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AsigPptariaSubt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(VBAdquisiciones)
                            .addComponent(VBFinanzas))
                        .addGap(58, 58, 58))))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void PeriUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeriUsoActionPerformed
// TODO add your handling code here:     
}//GEN-LAST:event_PeriUsoActionPerformed

private void CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_CargoActionPerformed

private void DtecnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DtecnumActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DtecnumActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    new GestionMenu().setVisible(true);
    this.setVisible(false);
    
}//GEN-LAST:event_jButton3ActionPerformed

private void DescipGeneDelProSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescipGeneDelProSerActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DescipGeneDelProSerActionPerformed

private void RecomendaProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecomendaProveActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_RecomendaProveActionPerformed

private void VBAdquisicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VBAdquisicionesActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_VBAdquisicionesActionPerformed

private void Cantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cantidad1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Cantidad1ActionPerformed

private void ValEstiToNe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValEstiToNe1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_ValEstiToNe1ActionPerformed

private void AsigPptariaSubtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsigPptariaSubtActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_AsigPptariaSubtActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here
        
    
        boolean ingreso= true;
        String FechaRecp1=  FechaRecep.getText();
      //String FechaRecp1=String.valueOf(jCalendarCombo1.getModel());
        String HoraRecep1= HoraRecep.getText();     
        boolean Recibe1= Recibe.isSelected();
        String Dtecnum1=  Dtecnum.getText();
        String Fecha =Fecha1.getText();
        String Solicitante1 = Solicitante.getText();
        String Cargo1 = Cargo.getText();
        String PeriUso1= PeriUso.getText();
        String Plazo="";
        if(SeisDias.isSelected()){
        Plazo="6";
        }
        if(DiezDias.isSelected()){
        Plazo="10";
        }
        if(VeinteDias.isSelected()){
        Plazo="20";
        }
        
        String Clase="";
        
        if(Producto.isSelected()){
        Clase="p";
        }
        if(TrabajoSer.isSelected()){
        Clase="ts";
        }
        if(AsesoConsul.isSelected()){
        Clase="ac";
        }
       
        String StockBode="";
       if(StockBodeSi.isSelected()){     
       StockBode="s";
       }
       if(StockBodeNo.isSelected()){
       StockBode="n";    
       }
       String DescipGeneDelProSer1=DescipGeneDelProSer.getText();
       String MotivosDelaNecesidadyDestino1=MotivosDelaNecesidadyDestino.getText();
       String RecomendaProve1= RecomendaProve.getText();
       String Anexo="";
      
       if(AnexoSi.isSelected()){     
       Anexo="s";
       }
       if(AnexoNo.isSelected()){
       Anexo="n";    
       }
        String AsigPptariaSubt1= AsigPptariaSubt.getText();
        String ItemAsignac1=ItemAsignac.getText(); 
        
        int Saldo1=0;
        
        if(!Saldo.getText().equals("")){
        try{
        Saldo1=Integer.parseInt(Saldo.getText());
        }catch(Exception e){    
        JOptionPane.showMessageDialog(this, "Debe ingresar solo numeros en el saldo", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        }
        }
        boolean vbffinanzas= VBFinanzas.isSelected(); 
        boolean vbaadquisiciones= VBAdquisiciones.isSelected();   
        Object depu = DeptoYUni.getSelectedItem();
        String DepUni = String.valueOf(depu);
        Object e = TipoCompra.getSelectedItem();
        String TipoC = String.valueOf(e);
        Object eo = MoDeRe.getSelectedItem();
        String MoDeR = String.valueOf(eo);
        Object eoi = ProBusOf.getSelectedItem();
        String ProBusO = String.valueOf(eoi);
        double ValEst1=0;
        double Vtp=0;
        double Imp=0;
        if(!ValEst.getText().equals("")){
         ValEst1=Double.parseDouble(ValEst.getText());  
         }
        if(!ValorTPesos.getText().equals("")){
         Vtp= Double.parseDouble(ValorTPesos.getText());
        }
        if(!Impuesto.getText().equals("")){
         Imp= Double.parseDouble(Impuesto.getText());   
        }
        
    if(Saldo1==0){
    JOptionPane.showMessageDialog(this, "Debe ingresar un numero en el saldo", "Advertencia", JOptionPane.OK_CANCEL_OPTION);      
    ingreso= false;
    }
    if(myMap==null){
        JOptionPane.showMessageDialog(this, "Debe ingresar algun producto o servicio a la lista", "Advertencia", JOptionPane.OK_CANCEL_OPTION);      
        ingreso= false;
    } 
     if(FechaRecep.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar la fecha para publicacion en mercadolibre.cl", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        FechaRecep.setBackground(Color.RED);
        ingreso= false;
    }
    if(HoraRecep.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar la hora para la publicacion en mercadolibre.cl", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        HoraRecep.setBackground(Color.RED);
        ingreso= false;
    }
    if(Dtecnum.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar el Numero del formulario de requerimiento", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        Dtecnum.setBackground(Color.RED);
        ingreso= false;
    }
    if(Fecha1.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar la Fecha del formulario", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        Fecha1.setBackground(Color.RED);
        ingreso= false;
    }  
    if(Solicitante.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar el solicitante", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        Solicitante.setBackground(Color.RED);
        ingreso= false;
    }
    if(Cargo.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar el Cargo", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        Cargo.setBackground(Color.RED);
        ingreso= false;
    }
    if(PeriUso.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar el Periodo de uso", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        PeriUso.setBackground(Color.RED);
        ingreso= false;
    }
    if(DescipGeneDelProSer.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar la descripcion general del producto/servicio", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        DescipGeneDelProSer.setBackground(Color.RED);
        ingreso= false;
    }
    if(MotivosDelaNecesidadyDestino.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar el motivo de necesidad y destino final del producto y/o servicio", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        MotivosDelaNecesidadyDestino.setBackground(Color.RED);
        ingreso= false;
    }
    if(RecomendaProve.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar Recomendacion de proveedores", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        RecomendaProve.setBackground(Color.RED);
        ingreso= false;
    }
    if(ingreso){
        boolean resul=cl.PruebaDeIngreso1(FechaRecp1,HoraRecep1,Recibe1,Dtecnum1,Fecha,DepUni,Solicitante1,Cargo1,PeriUso1,Plazo,Clase,TipoC,StockBode,DescipGeneDelProSer1,MotivosDelaNecesidadyDestino1,ProBusO,RecomendaProve1,MoDeR,Anexo,AsigPptariaSubt1,ItemAsignac1,Saldo1,vbffinanzas,vbaadquisiciones,ValEst1,Vtp,Imp);
        boolean result2=cl.AgregarListaDeDatos(myMap, Dtecnum.getText());     
        Mail m = new Mail("Se ha ingresado un nuevo formulario de requrimiento. Numero de formulario :"+ Dtecnum.getText()+" Usuario que lo ingresó :"+ Login.nom);
        m.send();// Mandar mensaje de modificacion de archivo  " Se ha ingresado el formulario de requerimiento numero:....por la cuenta con nombre:" 
        System.out.println("hasta acá llega la hora de la muerte");
        if(result2&&resul){//&&resul
        JOptionPane.showMessageDialog(this, "Se ha ingresado el formulario junto con su lista de productos de forma exitosa", "Informacion",ICONIFIED);  
        //FechaRecep.setText("")
        HoraRecep.setText("");     
        Recibe.setText("");
        int numero= cl.BuscarNumeroCorrelativo();
        String nm= String.valueOf(numero);
        Dtecnum.setText(nm);
        Fecha1.setText("");
        Solicitante.setText("");
        Cargo.setText("");
        FechaRecep.setText("");
        PeriUso.setText("");
        SeisDias.setSelected(false);
        DiezDias.setSelected(false);
        VeinteDias.setSelected(false);
        Producto.setSelected(false);
        TrabajoSer.setSelected(false);
        AsesoConsul.setSelected(false);
        StockBodeSi.setSelected(false);    
        StockBodeNo.setSelected(false);
        DescipGeneDelProSer.setText("");
        MotivosDelaNecesidadyDestino.setText("");
        RecomendaProve.setText("");
        AnexoSi.setSelected(false);
        AnexoNo.setSelected(false);
        AsigPptariaSubt.setText("");
        ItemAsignac.setText("");
        Saldo.setText("");
        VBFinanzas.setSelected(false); 
        VBAdquisiciones.setSelected(false);   
        ValEst.setText("");  
        ValorTPesos.setText("");
        Impuesto.setText("");
        jTable1.setModel(new DefaultTableModel());       
        myMap = new HashMap<String, String[]>();        
        }else{
           JOptionPane.showMessageDialog(this, "No se ha logrado ingresar el formulario, revise los campos de datos", "Informacion", JOptionPane.OK_OPTION);
           myMap=null;
           resultado=null;
           valor=0;
           sumaimp=0;
           }
    }else{
        JOptionPane.showMessageDialog(this, "No se ha logrado ingresar, revise los campos de datos", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
    
    }   
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    boolean ingreso =true;
    String[] nombreTabla= {"Descripcion En detalle del Requerimiento","Producto/Servicio","Cantidad","Valor moneda","Valor Estimado unitario Item Neto", "impuesto","Valor total Pesos"}; 
    try{
    int valor1=Integer.parseInt(Cantidad1.getText()); 
    }catch(NumberFormatException e){
     JOptionPane.showMessageDialog(this, "Debe ingresar solo numeros en los valores en las casillas numericas ", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
     ingreso= false;
    }
    if(Dtecnum.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Debe ingresar el Numero del formulario a buscar", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
      Dtecnum.setBackground(Color.RED);
      ingreso= false;
    }
    if(DescripDeReq1.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Debe ingresar la descripcion en detalle del requerimiento", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
      DescripDeReq1.setBackground(Color.RED);
      ingreso= false;
    }
     if(ProdSer1.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Debe ingresar el Producto/Servicio", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
      ProdSer1.setBackground(Color.RED);
      ingreso= false;
    }
    if(Cantidad1.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Debe ingresar la cantidad", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
      Cantidad1.setBackground(Color.RED);
      ingreso= false;
    }
    if(ValorMoneda1.getText().equals("")&&!!ValorMoneda.getSelectedItem().equals("Pesos")){
      JOptionPane.showMessageDialog(this, "Debe ingresar el Precio Estimado Unitario Neto", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
      ValorMoneda1.setBackground(Color.RED);
      ingreso= false;
    }  
    if(ValEstiToNe1.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Debe ingresar el Valor Estimado Total en Neto por Item", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
      ValEstiToNe1.setBackground(Color.RED);
      ingreso= false;
    }
    if(ValorMoneda1.getText().equals("")&&!ValorMoneda.getSelectedItem().equals("PESOS")){
      JOptionPane.showMessageDialog(this, "Debe ingresar el valor de la moneda de transaccion a pesos Chilenos", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
      ValorMoneda1.setBackground(Color.RED);
      ingreso= false;
    }
    double calculoPesos=0;
    
    
    if(!ValorMoneda1.getText().equals("")&&!DefineImpuesto.getSelectedItem().equals("PESOS") &&!ValorMoneda.getSelectedItem().equals("PESOS")){
    
        double vm=1;
        try{
         vm= Double.parseDouble(ValorMoneda1.getText());
       }catch(Exception e){    
        JOptionPane.showMessageDialog(this, "Debe ingresar solo numeros en el saldo", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
      // no puede acceder los productos por mal escrito
        ingreso= false;
       }
        
        double val=1;
        try{
         val= Double.parseDouble(ValEstiToNe1.getText());       
        }catch(Exception e){    
        JOptionPane.showMessageDialog(this, "Debe ingresar solo numeros en el saldo", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        ingreso=false;
        }
        
       calculoPesos= vm*val;
    }else{
        try{
            calculoPesos= Double.parseDouble(ValEstiToNe1.getText());    
         }catch(Exception e){    
        JOptionPane.showMessageDialog(this, "Debe ingresar solo numeros en el saldo", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        ingreso=false;
        }
    }
    
    double c=1;
     try{
      c= Double.parseDouble(Cantidad1.getText());
      }catch(Exception e){    
        JOptionPane.showMessageDialog(this, "Debe ingresar solo numeros en el saldo", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        ingreso=false;
      }
    double totalpesos= calculoPesos*c;
    
    double impues=0;
    double totaltotal=0;
    String tipoimp="";
    if(DefineImpuesto.getSelectedItem().equals("IVA 19%")){
     impues= totalpesos*0.19;
     totaltotal= totalpesos+impues;
    tipoimp="IVA 19% ";
    }
    if(DefineImpuesto.getSelectedItem().equals("Excento de Impuesto")){
     totaltotal= totalpesos;
      tipoimp="Sin Imp";
   
    }
    if(DefineImpuesto.getSelectedItem().equals("Impuesto 10%")){
     impues= totalpesos*0.10;
     totaltotal= totalpesos+impues;   
      tipoimp="Imp 10%";
   
    }
    String TPesos= String.valueOf(totalpesos);
    String CalculoImpuesto1= String.valueOf(impues);
    String TotalTotal1= String.valueOf(totaltotal);
    
    if(ingreso){
        
     
             resultado[0]= Dtecnum.getText();
             resultado[1]= DescripDeReq1.getText();
             resultado[2]= ProdSer1.getText(); 
             resultado[3]= Cantidad1.getText();
             if(!ValorMoneda.getSelectedItem().equals("PESOS")){
             resultado[4]= ValorMoneda.getSelectedItem()+"  "+ValorMoneda1.getText();
             }else{
             resultado[4]= ValorMoneda.getSelectedItem()+"  "+"Moneda Nacional"; 
             }
             resultado[5]= ValEstiToNe1.getText();
             resultado[6]= TPesos;           
             resultado[7]= tipoimp+" "+CalculoImpuesto1;
             resultado[8]= TotalTotal1;
             ingresoDatos.addRow(resultado);
             String nueva[]= new String[9];
             nueva[0]=resultado[0];
             nueva[1]= resultado[1];
             nueva[2]=resultado[2]; 
             nueva[3]=resultado[3];
             nueva[4]=resultado[4];
             nueva[5]=resultado[5];
             nueva[6]=resultado[6];
             nueva[7]=resultado[7];
             nueva[8]=resultado[8];
             String numero= String.valueOf(valor);
             System.out.println("el numero a guardar"+numero);
            
             myMap.put(numero, nueva);            
             valor++;
      
            jTable1.setModel(ingresoDatos);  
            DescripDeReq1.setText("");
            ProdSer1.setText(""); 
            Cantidad1.setText("");
            ValorMoneda1.setText("");
            ValEstiToNe1.setText("");
            double suma1=0;
            double suma2=0;
            double suma3=0;
            sumaimp=sumaimp+impues;
          
            for(int i=0; i<myMap.size();i++){
            String nombrenumero=String.valueOf(i);
            String [] vector= (String[]) myMap.get(nombrenumero);  
           // String ptotal=vector[6];
            String ptotal1=vector[6];
            String ptotal2=vector[7];
            String ptotal3=vector[8];
             suma1= suma1+ Double.parseDouble(ptotal1);
            //suma2= suma2+ Double.parseDouble(ptotal2);          
            suma3= suma3+ Double.parseDouble(ptotal3);
            }  
              //double impu=suma+(suma*0.19);
              //double imsolo=suma*0.19;
              String netossuma=String.valueOf(suma1);
              String impuestos=String.valueOf(sumaimp);  
              String netomasimpuestos=String.valueOf(suma3);
              //String im=String.valueOf(imsolo);
              //String sumaimp=String.valueOf(impu);
              ValorTPesos.setText(netossuma);
              Impuesto.setText(impuestos);
              ValEst.setText(netomasimpuestos); 
    }else{
        JOptionPane.showMessageDialog(this, "No se ha logrado ingresar, revise los campos de datos", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
    
    }    
}//GEN-LAST:event_jButton2ActionPerformed

private void TipoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoCompraActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TipoCompraActionPerformed

    private void FechaRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaRecepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaRecepActionPerformed

    private void DiezDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiezDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiezDiasActionPerformed

    private void VeinteDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeinteDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VeinteDiasActionPerformed

    private void DefineImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefineImpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefineImpuestoActionPerformed

    private void ValorMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorMonedaActionPerformed

    private void AnexoNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnexoNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnexoNoActionPerformed

    private void DeptoYUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeptoYUniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeptoYUniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ulti().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AnexoNo;
    private javax.swing.JRadioButton AnexoSi;
    private javax.swing.JRadioButton AsesoConsul;
    private javax.swing.JTextField AsigPptariaSubt;
    private javax.swing.JTextField Cantidad1;
    private javax.swing.JTextField Cargo;
    private javax.swing.JComboBox DefineImpuesto;
    private javax.swing.JComboBox DeptoYUni;
    private javax.swing.JTextField DescipGeneDelProSer;
    private javax.swing.JTextField DescripDeReq1;
    private javax.swing.JRadioButton DiezDias;
    private javax.swing.JTextField Dtecnum;
    private javax.swing.JTextField Fecha1;
    private javax.swing.JTextField FechaRecep;
    private javax.swing.JTextField HoraRecep;
    private javax.swing.JTextField Impuesto;
    private javax.swing.JTextField ItemAsignac;
    private javax.swing.JComboBox MoDeRe;
    private javax.swing.JTextField MotivosDelaNecesidadyDestino;
    private javax.swing.JTextField PeriUso;
    private javax.swing.JComboBox ProBusOf;
    private javax.swing.JTextField ProdSer1;
    private javax.swing.JRadioButton Producto;
    private javax.swing.JCheckBox Recibe;
    private javax.swing.JTextField RecomendaProve;
    private javax.swing.JTextField Saldo;
    private javax.swing.JRadioButton SeisDias;
    private javax.swing.JTextField Solicitante;
    private javax.swing.JRadioButton StockBodeNo;
    private javax.swing.JRadioButton StockBodeSi;
    private javax.swing.JComboBox TipoCompra;
    private javax.swing.JRadioButton TrabajoSer;
    private javax.swing.JCheckBox VBAdquisiciones;
    private javax.swing.JCheckBox VBFinanzas;
    private javax.swing.JTextField ValEst;
    private javax.swing.JTextField ValEstiToNe1;
    private javax.swing.JComboBox ValorMoneda;
    private javax.swing.JTextField ValorMoneda1;
    private javax.swing.JTextField ValorTPesos;
    private javax.swing.JRadioButton VeinteDias;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
